import os
import zipfile
from xml.sax.saxutils import escape


OUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "docs",
    "System_Health_Monitoring_System_Report.docx",
)


PARAGRAPHS = [
    ("A PROJECT REPORT ON", False, False),
    ("SYSTEM HEALTH MONITORING SYSTEM", False, False),
    ("Submitted in partial fulfillment of the requirements for the award of the degree of", False, False),
    ("BACHELOR OF COMPUTER APPLICATIONS (BCA)", False, False),
    ("", False, False),
    ("Submitted by", False, False),
    ("Student Name: __________________________", False, False),
    ("USN / Register Number: __________________________", False, False),
    ("", False, False),
    ("Under the Guidance of", False, False),
    ("Guide Name: __________________________", False, False),
    ("", False, False),
    ("Department of Computer Applications", False, False),
    ("College Name: __________________________", False, False),
    ("University Name: __________________________", False, False),
    ("Academic Year: 2025-2026", False, False),
    ("__PAGEBREAK__", False, False),
    ("CERTIFICATE", True, False),
    ("This is to certify that the project work entitled \"System Health Monitoring System\" is a bonafide record of the work carried out by Mr./Ms. __________________________, bearing USN/Register Number __________________________, in partial fulfillment of the requirements for the award of the degree of Bachelor of Computer Applications, under __________________________ University, during the academic year 2025-2026.", False, False),
    ("The project work has been completed under my guidance and supervision.", False, False),
    ("", False, False),
    ("Guide Signature: ____________________", False, False),
    ("Guide Name: ____________________", False, False),
    ("Designation: ____________________", False, False),
    ("Head of Department: ____________________", False, False),
    ("Principal: ____________________", False, False),
    ("College Seal", False, False),
    ("Place: ____________", False, False),
    ("Date: ____________", False, False),
    ("__PAGEBREAK__", False, False),
    ("DECLARATION", True, False),
    ("I hereby declare that the project report entitled \"System Health Monitoring System\" submitted to __________________________ University in partial fulfillment of the requirements for the award of the degree of Bachelor of Computer Applications (BCA) is an original work carried out by me under the guidance of __________________________.", False, False),
    ("I further declare that this work has not been submitted earlier to any university or institution for the award of any degree, diploma, or certificate.", False, False),
    ("", False, False),
    ("Place: ____________", False, False),
    ("Date: ____________", False, False),
    ("Student Signature: ____________________", False, False),
    ("Name: ____________________", False, False),
    ("__PAGEBREAK__", False, False),
    ("ACKNOWLEDGEMENT", True, False),
    ("I express my sincere gratitude to my project guide __________________________ for the valuable guidance, support, and encouragement provided throughout the development of this project.", False, False),
    ("I also thank the Head of the Department, principal, and all faculty members of the Department of Computer Applications for their guidance and support.", False, False),
    ("I am grateful to my parents, friends, and classmates for their encouragement and help during the completion of this project.", False, False),
    ("Finally, I thank everyone who directly or indirectly contributed to the successful completion of the project \"System Health Monitoring System.\"", False, False),
    ("__PAGEBREAK__", False, False),
    ("ABSTRACT", True, False),
    ("The System Health Monitoring System is a desktop-based application developed to monitor the performance and health of a computer system in real time. The system tracks major system resources such as CPU usage, memory usage, disk usage, and process activity. It also provides alerts, historical data storage, suggestions for improvement, and report generation.", False, False),
    ("In many cases, users monitor their systems manually using built-in tools such as Task Manager. Manual monitoring is not continuous and may fail to identify sudden resource spikes or long-term performance trends. The proposed system automates the monitoring process and provides a user-friendly dashboard for live observation and analysis.", False, False),
    ("This project is useful for personal computers, office systems, educational labs, and small server environments. It helps users identify system slowdowns, excessive memory usage, abnormal CPU usage, and storage problems at an early stage.", False, False),
    ("The project is developed using Python, PySide6, SQLite, psutil, and scikit-learn. It combines practical system monitoring with simple analytics and a clean desktop interface.", False, False),
    ("__PAGEBREAK__", False, False),
    ("INDEX", True, False),
    ("1. Introduction", False, False),
    ("2. Problem Statement", False, False),
    ("3. Objectives", False, False),
    ("4. Scope of the Project", False, False),
    ("5. Literature Survey", False, False),
    ("6. System Analysis", False, False),
    ("7. System Design", False, False),
    ("8. Architecture Diagram", False, False),
    ("9. Data Flow Diagram", False, False),
    ("10. ER Diagram", False, False),
    ("11. Modules Description", False, False),
    ("12. Technologies Used", False, False),
    ("13. Implementation", False, False),
    ("14. Code Snippets", False, False),
    ("15. Algorithm / Workflow", False, False),
    ("16. Output Screens", False, False),
    ("17. Testing", False, False),
    ("18. Results and Discussion", False, False),
    ("19. Future Enhancements", False, False),
    ("20. Conclusion", False, False),
    ("21. References", False, False),
    ("22. Appendix", False, False),
    ("", False, False),
    ("TABLE OF CONTENTS", True, False),
    ("Chapter No.    Title                                   Page No.", False, True),
    ("1             Introduction                            ___", False, True),
    ("2             Problem Statement                       ___", False, True),
    ("3             Objectives                              ___", False, True),
    ("4             Scope of the Project                    ___", False, True),
    ("5             Literature Survey                       ___", False, True),
    ("6             System Analysis                         ___", False, True),
    ("7             System Design                           ___", False, True),
    ("8             Architecture Diagram                    ___", False, True),
    ("9             Data Flow Diagram                       ___", False, True),
    ("10            ER Diagram                              ___", False, True),
    ("11            Modules Description                     ___", False, True),
    ("12            Technologies Used                       ___", False, True),
    ("13            Implementation                          ___", False, True),
    ("14            Code Snippets                           ___", False, True),
    ("15            Algorithm / Workflow                    ___", False, True),
    ("16            Output Screens                          ___", False, True),
    ("17            Testing                                 ___", False, True),
    ("18            Results and Discussion                  ___", False, True),
    ("19            Future Enhancements                     ___", False, True),
    ("20            Conclusion                              ___", False, True),
    ("21            References                              ___", False, True),
    ("22            Appendix                                ___", False, True),
    ("", False, False),
    ("1. INTRODUCTION", True, False),
    ("1.1 Meaning of System Health Monitoring", False, False),
    ("System Health Monitoring means continuously checking the condition of a computer system by observing important hardware and software resource values. It helps us know how a system is performing at any given time.", False, False),
    ("The main resources commonly monitored are CPU usage, memory usage, disk usage, running processes, system alerts, and health status.", False, False),
    ("1.2 Need for System Health Monitoring", False, False),
    ("Modern computer systems run many applications, background services, and user tasks at the same time. When multiple programs consume too many resources, the system becomes slow and may stop responding. Without proper monitoring, it becomes difficult to identify the exact cause of the problem.", False, False),
    ("System health monitoring helps in detecting heavy CPU usage, excessive memory consumption, low disk space, abnormal process activity, and overall system instability.", False, False),
    ("1.3 Importance in IT Systems", False, False),
    ("System monitoring is important in IT systems because performance problems can affect daily work and productivity. In companies and educational institutions, systems must work properly for long hours. Monitoring helps avoid unexpected failure.", False, False),
    ("1.4 Real-World Applications", False, False),
    ("This system can be used in personal computers, college laboratories, office desktops, administrative systems, and small business environments.", False, False),
    ("", False, False),
    ("2. PROBLEM STATEMENT", True, False),
    ("In most systems, users depend on manual observation through tools like Task Manager or Resource Monitor. These tools show current performance values but they do not always provide continuous tracking, alerting, or intelligent analysis.", False, False),
    ("The major problems in manual monitoring are: monitoring is not continuous, sudden spikes may go unnoticed, historical records are not maintained properly, normal users may not understand technical details, and there is no simple report generation for performance review.", False, False),
    ("Therefore, the proposed project aims to design and develop a System Health Monitoring System that automates system resource monitoring and improves practical usability.", False, False),
    ("", False, False),
    ("3. OBJECTIVES", True, False),
    ("The main objectives of the project are:", False, False),
    ("- To monitor CPU usage in real time", False, False),
    ("- To monitor memory usage in real time", False, False),
    ("- To monitor disk usage and available space", False, False),
    ("- To analyze running processes", False, False),
    ("- To generate alerts for abnormal conditions", False, False),
    ("- To store system metrics in a database", False, False),
    ("- To display system information through a dashboard", False, False),
    ("- To provide graphs and history view", False, False),
    ("- To generate reports for analysis", False, False),
    ("- To assist users in performance optimization", False, False),
    ("", False, False),
    ("4. SCOPE OF THE PROJECT", True, False),
    ("The project can be used in personal computers, college laboratories, office desktops, administrative systems, local servers, and small business systems.", False, False),
    ("The functional scope includes resource monitoring, process tracking, alerts and notifications, historical record maintenance, report generation, performance suggestions, startup program analysis, and cache cleanup suggestions.", False, False),
    ("The current scope is limited to single-machine monitoring, desktop-based usage, Windows-oriented behavior, and basic machine learning support.", False, False),
    ("", False, False),
    ("5. LITERATURE SURVEY", True, False),
    ("Existing monitoring tools include Nagios, Zabbix, Windows Task Manager, and Resource Monitor.", False, False),
    ("Nagios and Zabbix are powerful enterprise tools but may be complex for simple academic or personal use. Built-in tools are simple but do not provide integrated alerts, reporting, or suggestions.", False, False),
    ("Comparison Table:", False, False),
    ("Tool             Monitoring   Alerts   History   Ease of Use", False, True),
    ("Nagios           Yes          Yes      Yes       Moderate", False, True),
    ("Zabbix           Yes          Yes      Yes       Moderate", False, True),
    ("Task Manager     Yes          Limited  No        Easy", False, True),
    ("Resource Monitor Yes          No       Limited   Moderate", False, True),
    ("Proposed System  Yes          Yes      Yes       Easy", False, True),
    ("", False, False),
    ("6. SYSTEM ANALYSIS", True, False),
    ("The existing system is mainly manual and depends on built-in tools. Users must open Task Manager or similar applications to inspect system performance.", False, False),
    ("The proposed system is an automated desktop application that monitors system resources continuously and presents them in an understandable format.", False, False),
    ("Advantages of the proposed system include easy usage, time saving, practical utility, better system awareness, and support for performance optimization.", False, False),
    ("", False, False),
    ("7. SYSTEM DESIGN", True, False),
    ("The design of the project includes user interface, monitoring engine, database storage, alert system, suggestions engine, and report generation module. The system follows a modular structure so that each component can be developed and maintained separately.", False, False),
    ("", False, False),
    ("8. ARCHITECTURE DIAGRAM", True, False),
    ("Text-Based Architecture:", False, False),
    ("+---------+      +------------------+      +----------------------+", False, True),
    ("|  User   | ---> |   UI Dashboard   | ---> |   Backend Services   |", False, True),
    ("+---------+      +------------------+      +----------------------+", False, True),
    ("                                                    |", False, True),
    ("             +----------------+---------------------+----------------+", False, True),
    ("             |                |                     |                |", False, True),
    ("             v                v                     v                v", False, True),
    ("      +-----------+    +-------------+      +-------------+   +-----------+", False, True),
    ("      | Monitoring|    | Alert System|      | Suggestions |   | Reports   |", False, True),
    ("      +-----------+    +-------------+      +-------------+   +-----------+", False, True),
    ("             |", False, True),
    ("             v", False, True),
    ("      +-----------------------------+", False, True),
    ("      | CPU / Memory / Disk / Proc |", False, True),
    ("      +-----------------------------+", False, True),
    ("             |", False, True),
    ("             v", False, True),
    ("      +-----------------------------+", False, True),
    ("      |         SQLite DB           |", False, True),
    ("      +-----------------------------+", False, True),
    ("", False, False),
    ("9. DATA FLOW DIAGRAM", True, False),
    ("DFD Level 0:", False, False),
    ("          +--------+", False, True),
    ("          |  User  |", False, True),
    ("          +---+----+", False, True),
    ("              |", False, True),
    ("              v", False, True),
    ("   +---------------------------+", False, True),
    ("   | System Health Monitoring  |", False, True),
    ("   |         System            |", False, True),
    ("   +---------------------------+", False, True),
    ("      |          |         |", False, True),
    ("      v          v         v", False, True),
    ("  Metrics      Alerts    Reports", False, True),
    ("      \\\\          |         /", False, True),
    ("       \\\\         |        /", False, True),
    ("        v        v       v", False, True),
    ("          +---------------+", False, True),
    ("          |   Database    |", False, True),
    ("          +---------------+", False, True),
    ("DFD Level 1:", False, False),
    ("+--------+     +------------------+     +-----------------+", False, True),
    ("|  User  | --> | Dashboard Module | --> | Display Metrics |", False, True),
    ("+--------+     +------------------+     +-----------------+", False, True),
    ("", False, True),
    ("                +------------------+", False, True),
    ("                | Monitoring Module|", False, True),
    ("                +------------------+", False, True),
    ("                 |   |    |    |", False, True),
    ("                 v   v    v    v", False, True),
    ("                CPU RAM Disk Process", False, True),
    ("", False, True),
    ("                +------------------+", False, True),
    ("                | Alert Module     |", False, True),
    ("                +------------------+", False, True),
    ("                        |", False, True),
    ("                        v", False, True),
    ("                   Notifications", False, True),
    ("", False, True),
    ("                +------------------+", False, True),
    ("                | Database Module  |", False, True),
    ("                +------------------+", False, True),
    ("                        |", False, True),
    ("                        v", False, True),
    ("            Metrics / Alerts / Settings / Notes", False, True),
    ("", False, True),
    ("                +------------------+", False, True),
    ("                | Report Module    |", False, True),
    ("                +------------------+", False, True),
    ("                        |", False, True),
    ("                        v", False, True),
    ("                    PDF Report", False, True),
    ("", False, False),
    ("10. ER DIAGRAM", True, False),
    ("+------------------+", False, True),
    ("| SYSTEM_METRICS   |", False, True),
    ("+------------------+", False, True),
    ("| id (PK)          |", False, True),
    ("| timestamp        |", False, True),
    ("| cpu_usage        |", False, True),
    ("| memory_usage     |", False, True),
    ("| disk_usage       |", False, True),
    ("| process_count    |", False, True),
    ("+------------------+", False, True),
    ("", False, True),
    ("+------------------+", False, True),
    ("| ALERTS           |", False, True),
    ("+------------------+", False, True),
    ("| id (PK)          |", False, True),
    ("| timestamp        |", False, True),
    ("| severity         |", False, True),
    ("| message          |", False, True),
    ("| source           |", False, True),
    ("| acknowledged     |", False, True),
    ("+------------------+", False, True),
    ("", False, True),
    ("+------------------+", False, True),
    ("| USER_SETTINGS    |", False, True),
    ("+------------------+", False, True),
    ("| id (PK)          |", False, True),
    ("| feature          |", False, True),
    ("| value            |", False, True),
    ("| updated_at       |", False, True),
    ("+------------------+", False, True),
    ("", False, True),
    ("+------------------+", False, True),
    ("| PROCESS_HISTORY  |", False, True),
    ("+------------------+", False, True),
    ("| id (PK)          |", False, True),
    ("| timestamp        |", False, True),
    ("| pid              |", False, True),
    ("| process_name     |", False, True),
    ("| cpu_percent      |", False, True),
    ("| memory_mb        |", False, True),
    ("| memory_percent   |", False, True),
    ("+------------------+", False, True),
    ("", False, True),
    ("+------------------+", False, True),
    ("| ADMIN_NOTES      |", False, True),
    ("+------------------+", False, True),
    ("| id (PK)          |", False, True),
    ("| timestamp        |", False, True),
    ("| target_date      |", False, True),
    ("| note_text        |", False, True),
    ("+------------------+", False, True),
    ("", False, False),
    ("11. MODULES DESCRIPTION", True, False),
    ("Data Collection Module: Collects CPU, memory, disk, and process values using the psutil library.", False, False),
    ("Monitoring Module: Continuously checks system values, updates the dashboard, and calculates health score.", False, False),
    ("Alert Module: Compares values with thresholds and generates warnings for high or critical conditions.", False, False),
    ("Dashboard UI Module: Displays live values, history, graphs, settings, suggestions, and notes.", False, False),
    ("Report Module: Generates PDF reports containing metrics, health score, anomalies, suggestions, and summary data.", False, False),
    ("Database Module: Stores metrics, alerts, settings, and notes in SQLite.", False, False),
    ("", False, False),
    ("12. TECHNOLOGIES USED", True, False),
    ("Technology        Purpose", False, True),
    ("Python            Main programming language", False, True),
    ("PySide6           Desktop GUI", False, True),
    ("SQLite            Local database", False, True),
    ("psutil            System resource monitoring", False, True),
    ("scikit-learn      Anomaly detection", False, True),
    ("pyqtgraph         Real-time graphs", False, True),
    ("matplotlib        Graph fallback", False, True),
    ("QSS               UI styling", False, True),
    ("", False, False),
    ("13. IMPLEMENTATION", True, False),
    ("The implementation was carried out in stages: environment setup, monitoring logic development, database integration, dashboard design, alert and suggestions engine creation, and report generation.", False, False),
    ("Required libraries include PySide6, psutil, scikit-learn, pyqtgraph, and matplotlib. SQLite is used as the backend database.", False, False),
    ("", False, False),
    ("14. IMPORTANT CODE SNIPPETS", True, False),
    ("CPU Monitoring:", False, False),
    ("def get_current_usage(self):", False, True),
    ("    cpu_percent = psutil.cpu_percent(interval=0.1)", False, True),
    ("    return min(100.0, max(0.0, cpu_percent))", False, True),
    ("", False, True),
    ("Memory Monitoring:", False, False),
    ("def get_current_usage(self):", False, True),
    ("    memory = psutil.virtual_memory()", False, True),
    ("    return memory.percent", False, True),
    ("", False, True),
    ("Disk Monitoring:", False, False),
    ("def get_current_usage(self, drive='C:'):", False, True),
    ("    disk = psutil.disk_usage(drive)", False, True),
    ("    return disk.percent", False, True),
    ("", False, True),
    ("Insert Metrics into Database:", False, False),
    ("cursor.execute(\"\"\"", False, True),
    ("    INSERT INTO system_metrics (timestamp, cpu_usage, memory_usage, disk_usage, process_count)", False, True),
    ("    VALUES (?, ?, ?, ?, ?)", False, True),
    ("\"\"\", (local_ts, cpu_usage, memory_usage, disk_usage, process_count))", False, True),
    ("", False, False),
    ("15. ALGORITHM / WORKFLOW", True, False),
    ("Step-by-Step Working:", False, False),
    ("1. Initialize application.", False, False),
    ("2. Start background monitoring worker.", False, False),
    ("3. Read CPU, memory, disk, and process data.", False, False),
    ("4. Update dashboard values.", False, False),
    ("5. Compare values with threshold settings.", False, False),
    ("6. Detect abnormal conditions.", False, False),
    ("7. Generate alerts if needed.", False, False),
    ("8. Save values to database.", False, False),
    ("9. Show suggestions and summaries.", False, False),
    ("10. Generate report when requested.", False, False),
    ("Workflow Diagram:", False, False),
    ("Start", False, True),
    ("  |", False, True),
    ("  v", False, True),
    ("Initialize Modules", False, True),
    ("  |", False, True),
    ("  v", False, True),
    ("Collect System Metrics", False, True),
    ("  |", False, True),
    ("  v", False, True),
    ("Analyze Data", False, True),
    ("  |", False, True),
    ("  +---- Normal ------> Update Dashboard", False, True),
    ("  |", False, True),
    ("  +---- Abnormal ---> Generate Alert", False, True),
    ("                       |", False, True),
    ("                       v", False, True),
    ("                  Save in Database", False, True),
    ("                       |", False, True),
    ("                       v", False, True),
    ("                Show Suggestions", False, True),
    ("                       |", False, True),
    ("                       v", False, True),
    ("                  Generate Report", False, True),
    ("                       |", False, True),
    ("                       v", False, True),
    ("                      End", False, True),
    ("", False, False),
    ("16. OUTPUT SCREENS", True, False),
    ("Dashboard Screen: Shows live CPU, memory, disk, and health status values.", False, False),
    ("Alerts Screen: Shows alert type, time, severity, description, and acknowledgement status.", False, False),
    ("History Screen: Shows stored records using time-based filters.", False, False),
    ("Suggestions Screen: Shows startup analysis, cache cleanup analysis, and live recommendations.", False, False),
    ("Settings Screen: Allows configuration of refresh interval, alert cooldown, theme, and monitoring options.", False, False),
    ("Notes Screen: Allows adding and maintaining administrative notes.", False, False),
    ("", False, False),
    ("17. TESTING", True, False),
    ("Test Case    Input / Action         Expected Output             Actual Output           Status", False, True),
    ("1            Run application        Main window opens           Opened successfully     Pass", False, True),
    ("2            Read CPU usage         Current CPU shown           Displayed correctly     Pass", False, True),
    ("3            Read memory usage      Current RAM shown           Displayed correctly     Pass", False, True),
    ("4            Save metric            Record inserted into DB     Inserted                Pass", False, True),
    ("5            Trigger alert          Warning displayed           Displayed               Pass", False, True),
    ("6            Open history           Past records loaded         Loaded                  Pass", False, True),
    ("7            Generate report        PDF report created          Created                 Pass", False, True),
    ("8            Open settings          Settings loaded             Loaded                  Pass", False, True),
    ("9            View process table     Processes listed            Listed                  Pass", False, True),
    ("10           Add note               Note saved                  Saved                   Pass", False, True),
    ("The application was tested in a Windows environment using available verification scripts and manual checking. The main modules worked successfully and the system performed as expected.", False, False),
    ("", False, False),
    ("18. RESULTS AND DISCUSSION", True, False),
    ("The application performs well for desktop-level monitoring. Background monitoring helps keep the UI responsive. The system updates metrics regularly and stores useful data for future analysis.", False, False),
    ("Since the project uses psutil, the CPU, memory, and disk usage values are reasonably accurate and reliable.", False, False),
    ("The project successfully achieves its main goals: continuous monitoring, user-friendly dashboard, alerts, database storage, suggestions, and report generation.", False, False),
    ("", False, False),
    ("19. FUTURE ENHANCEMENTS", True, False),
    ("- AI-based prediction of failures", False, False),
    ("- Mobile application support", False, False),
    ("- Remote and cloud monitoring", False, False),
    ("- Email and SMS alerts", False, False),
    ("- Multi-system dashboard", False, False),
    ("- Advanced analytics", False, False),
    ("- Web-based version", False, False),
    ("- Role-based user access", False, False),
    ("", False, False),
    ("20. CONCLUSION", True, False),
    ("The System Health Monitoring System is a practical desktop application developed for monitoring computer health and performance. It helps users identify resource problems and understand system behavior in real time.", False, False),
    ("The project automates the process of observing CPU, memory, disk, and process activity. It also provides alerts, history, reports, and suggestions, which make it more useful than basic manual monitoring tools.", False, False),
    ("This project demonstrates the effective use of Python, GUI development, database handling, and system monitoring concepts. It is a suitable and meaningful BCA final-year project under the NEP syllabus.", False, False),
    ("", False, False),
    ("21. REFERENCES", True, False),
    ("1. Python Software Foundation. Python Documentation. https://docs.python.org/", False, False),
    ("2. Qt for Python Team. PySide6 Documentation. https://doc.qt.io/qtforpython/", False, False),
    ("3. psutil Developers. psutil Documentation. https://psutil.readthedocs.io/", False, False),
    ("4. SQLite Consortium. SQLite Documentation. https://www.sqlite.org/docs.html", False, False),
    ("5. scikit-learn Developers. scikit-learn Documentation. https://scikit-learn.org/", False, False),
    ("6. Reference study of Nagios, Zabbix, Windows Task Manager, and Resource Monitor.", False, False),
    ("", False, False),
    ("22. APPENDIX", True, False),
    ("Project Structure:", False, False),
    ("system-health-monetoring/", False, True),
    ("├── main.py", False, True),
    ("├── config.py", False, True),
    ("├── requirements.txt", False, True),
    ("├── monitor/", False, True),
    ("├── analysis/", False, True),
    ("├── backend/", False, True),
    ("├── alerts/", False, True),
    ("├── ui/", False, True),
    ("├── tests/", False, True),
    ("├── themes/", False, True),
    ("└── docs/", False, True),
    ("", False, False),
    ("Sample Viva Questions:", False, False),
    ("- What is system health monitoring?", False, False),
    ("- Why is Python used in this project?", False, False),
    ("- What is the role of psutil?", False, False),
    ("- Why is SQLite used?", False, False),
    ("- What are the main modules?", False, False),
    ("- How are alerts generated?", False, False),
    ("- What future enhancements can be added?", False, False),
    ("", False, False),
    ("Signature Page", False, False),
    ("Student Signature: ____________________", False, False),
    ("Guide Signature: ____________________", False, False),
    ("HOD Signature: ____________________", False, False),
    ("Principal Signature: ____________________", False, False),
]


def para_xml(text, bold=False, mono=False):
    if text == "__PAGEBREAK__":
        return '<w:p><w:r><w:br w:type="page"/></w:r></w:p>'
    if text == "":
        return "<w:p/>"

    props = ""
    if mono:
        props += '<w:rFonts w:ascii="Consolas" w:hAnsi="Consolas"/>'
    if bold:
        props += "<w:b/>"
    rpr = f"<w:rPr>{props}</w:rPr>" if props else ""
    return f'<w:p><w:r>{rpr}<w:t xml:space="preserve">{escape(text)}</w:t></w:r></w:p>'


def build_docx():
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    body = "".join(para_xml(text, bold, mono) for text, bold, mono in PARAGRAPHS)

    document_xml = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 wp14">
  <w:body>
    {body}
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/>
    </w:sectPr>
  </w:body>
</w:document>"""

    content_types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>"""

    rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>"""

    core = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>System Health Monitoring System Report</dc:title>
  <dc:subject>BCA Final Year Project Report</dc:subject>
  <dc:creator>Mallikarjun</dc:creator>
  <cp:keywords>System Health Monitoring, BCA, Project Report</cp:keywords>
  <dc:description>Academic project report for System Health Monitoring System</dc:description>
  <cp:lastModifiedBy>Mallikarjun</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">2026-04-20T00:00:00Z</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">2026-04-20T00:00:00Z</dcterms:modified>
</cp:coreProperties>"""

    app = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Microsoft Office Word</Application>
</Properties>"""

    with zipfile.ZipFile(OUT_PATH, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("docProps/core.xml", core)
        zf.writestr("docProps/app.xml", app)
        zf.writestr("word/document.xml", document_xml)


if __name__ == "__main__":
    build_docx()
    print(OUT_PATH)
